name: Deploy Strapi with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag of the ECR image to deploy"
        required: true
        default: "latest"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 301782007642
      ECR_REPOSITORY: strapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR login token
        id: ecr-token
        run: |
          echo "token=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: task_5/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: task_5/terraform
        run: |
          terraform plan \
            -var="image_tag=${{ github.event.inputs.image_tag }}" \
            -var="ecr_token=${{ steps.ecr-token.outputs.token }}"

      - name: Terraform Apply
        working-directory: task_5/terraform
        run: |
          terraform apply -auto-approve \
            -var="image_tag=${{ github.event.inputs.image_tag }}" \
            -var="ecr_token=${{ steps.ecr-token.outputs.token }}"
